services:
  database:
    image: postgres:16
    container_name: learning-platform-db
    env_file: ".env"
    volumes:
      - learning_platform_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - learningplatform
  api:
    build:
      context: ../learn-ops-api
      dockerfile: Dockerfile
    container_name: learning-platform-api
    env_file: "../learn-ops-api/.env"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../learn-ops-api:/app
    networks:
      - learningplatform
  client:
    build:
      context: ../learn-ops-client
      dockerfile: Dockerfile
    container_name: learning-platform-client
    env_file: "../learn-ops-client/.env"
    ports:
      - "3000:3000"
    volumes:
      - ../learn-ops-client:/app
      - /app/node_modules
    networks:
      - learningplatform
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api # Prometheus will scrape metrics from your Django 'api' service
    networks:
      - learningplatform

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # Changed host port from 3000 to 3001
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - learningplatform
volumes:
  learning_platform_data:
  grafana_data:
networks:
  learningplatform:
    external: true
