services:
  database:
    image: postgres:16
    container_name: learning-platform-db
    env_file: ".env"
    volumes:
      - learning_platform_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - learningplatform
  api:
    build:
      context: ../learn-ops-api
      dockerfile: Dockerfile
    container_name: learning-platform-api
    env_file: "../learn-ops-api/.env"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../learn-ops-api:/app
    networks:
      - learningplatform
  client:
    build:
      context: ../learn-ops-client
      dockerfile: Dockerfile
    container_name: learning-platform-client
    env_file: "../learn-ops-client/.env"
    ports:
      - "3000:3000"
    volumes:
      - ../learn-ops-client:/app
      - /app/node_modules
    networks:
      - learningplatform
volumes:
  learning_platform_data:
networks:
  learningplatform:
    external: true
